#!/usr/bin/env python3
"""
Telemetry Log Analyzer for Mission Dive
=========================================
Analyzes the CSV log generated by mission_dive_autonomous.py

Usage:
    python3 analyze_log.py mission_dive_20260109_183000.csv
"""

import sys
import pandas as pd
import numpy as np

def analyze_log(filename):
    """Analyze mission telemetry log"""
    print("="*60)
    print("📊 MISSION DIVE TELEMETRY ANALYSIS")
    print("="*60)
    print(f"File: {filename}\n")
    
    # Load data
    try:
        df = pd.read_csv(filename)
    except Exception as e:
        print(f"❌ Error loading file: {e}")
        return
    
    # Overall stats
    print(f"Total records: {len(df)}")
    print(f"Duration: {(len(df) * 0.05):.1f} seconds (approx)\n")
    
    # Phase 1: ASCENT
    print("─" * 60)
    print("🚀 PHASE 1: ASCENT")
    print("─" * 60)
    ascent = df[df['phase'] == 'ASCENT']
    
    if len(ascent) > 0:
        max_alt = ascent['altitude_m'].max()
        min_alt = ascent['altitude_m'].min()
        avg_climb = ascent['vertical_speed_m_s'].mean()
        max_climb = ascent['vertical_speed_m_s'].max()
        duration = len(ascent) * 0.05
        
        print(f"Altitude range: {min_alt:.1f}m → {max_alt:.1f}m")
        print(f"Climb rate (avg): {abs(avg_climb):.2f} m/s (target: 6.0 m/s)")
        print(f"Climb rate (max): {abs(max_climb):.2f} m/s")
        print(f"Duration: {duration:.1f} seconds")
        
        # Validation
        if max_alt >= 68 and max_alt <= 72:
            print("✅ Altitude target achieved (70m ± 2m)")
        else:
            print(f"⚠️  Altitude off target: {max_alt:.1f}m (expected: 70m)")
        
        if abs(avg_climb) >= 5.5 and abs(avg_climb) <= 6.5:
            print("✅ Climb rate within spec (6 m/s ± 0.5 m/s)")
        else:
            print(f"⚠️  Climb rate off target: {abs(avg_climb):.2f} m/s")
    else:
        print("⚠️  No ASCENT data found")
    
    # Phase 2: HOVER
    print("\n" + "─" * 60)
    print("🛰️  PHASE 2: HOVER")
    print("─" * 60)
    hover = df[df['phase'] == 'HOVER']
    
    if len(hover) > 0:
        avg_alt = hover['altitude_m'].mean()
        std_alt = hover['altitude_m'].std()
        avg_horiz_speed = hover['horizontal_speed_m_s'].mean()
        duration = len(hover) * 0.05
        
        print(f"Average altitude: {avg_alt:.1f}m")
        print(f"Altitude stability (σ): {std_alt:.2f}m")
        print(f"Average horizontal drift: {avg_horiz_speed:.2f} m/s")
        print(f"Duration: {duration:.1f} seconds")
        
        # Validation
        if duration >= 4.5 and duration <= 5.5:
            print("✅ Hover duration on target (5s ± 0.5s)")
        else:
            print(f"⚠️  Hover duration off target: {duration:.1f}s")
        
        if std_alt < 1.0:
            print("✅ Good altitude stability")
        else:
            print(f"⚠️  High altitude fluctuation: {std_alt:.2f}m")
    else:
        print("⚠️  No HOVER data found")
    
    # Phase 3: DIVE
    print("\n" + "─" * 60)
    print("⬇️  PHASE 3: DIVE")
    print("─" * 60)
    dive = df[df['phase'] == 'DIVE']
    
    if len(dive) > 0:
        max_alt = dive['altitude_m'].max()
        min_alt = dive['altitude_m'].min()
        avg_descent = dive['vertical_speed_m_s'].mean()
        max_descent = dive['vertical_speed_m_s'].max()
        avg_forward = dive['horizontal_speed_m_s'].mean()
        
        # Calculate dive angle from velocity
        if avg_forward > 0:
            dive_angle = np.degrees(np.arctan(avg_descent / avg_forward))
        else:
            dive_angle = 90.0  # Vertical
        
        duration = len(dive) * 0.05
        
        print(f"Altitude range: {max_alt:.1f}m → {min_alt:.1f}m")
        print(f"Descent rate (avg): {avg_descent:.2f} m/s (target: 5.0 m/s)")
        print(f"Descent rate (max): {max_descent:.2f} m/s")
        print(f"Forward speed (avg): {avg_forward:.2f} m/s")
        print(f"Calculated dive angle: {dive_angle:.1f}° (target: 35°)")
        print(f"Duration: {duration:.1f} seconds")
        
        # Validation
        if avg_descent >= 4.5 and avg_descent <= 5.5:
            print("✅ Descent rate within spec (5 m/s ± 0.5 m/s)")
        else:
            print(f"⚠️  Descent rate off target: {avg_descent:.2f} m/s")
        
        if dive_angle >= 30 and dive_angle <= 40:
            print("✅ Dive angle on target (35° ± 5°)")
        else:
            print(f"⚠️  Dive angle off target: {dive_angle:.1f}°")
        
        # Check pitch attitude
        avg_pitch = dive['pitch_deg'].mean()
        print(f"\nAverage pitch: {avg_pitch:.1f}°")
        
        if abs(avg_pitch) < 50:
            print("✅ Pitch within safety limits")
        else:
            print(f"⚠️  High pitch angle: {abs(avg_pitch):.1f}°")
    else:
        print("⚠️  No DIVE data found")
    
    # Phase 4: RECOVERY
    print("\n" + "─" * 60)
    print("🛬 PHASE 4: RECOVERY")
    print("─" * 60)
    recovery = df[df['phase'] == 'RECOVERY']
    
    if len(recovery) > 0:
        final_alt = recovery['altitude_m'].iloc[-1]
        print(f"Final altitude: {final_alt:.1f}m")
        
        if final_alt >= MIN_SAFE_ALTITUDE:
            print(f"✅ Safely above abort altitude ({MIN_SAFE_ALTITUDE}m)")
        else:
            print(f"⚠️  Below safe altitude: {final_alt:.1f}m")
    else:
        print("⚠️  No RECOVERY data found")
    
    # Summary
    print("\n" + "="*60)
    print("📋 MISSION SUMMARY")
    print("="*60)
    
    phases_found = df['phase'].unique()
    expected_phases = ['ASCENT', 'HOVER', 'DIVE', 'RECOVERY']
    
    print(f"Phases completed: {', '.join(phases_found)}")
    
    all_phases = all(phase in phases_found for phase in expected_phases)
    if all_phases:
        print("✅ All mission phases completed successfully")
    else:
        missing = set(expected_phases) - set(phases_found)
        print(f"⚠️  Missing phases: {', '.join(missing)}")
    
    print("="*60)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 analyze_log.py <log_file.csv>")
        sys.exit(1)
    
    MIN_SAFE_ALTITUDE = 5.0  # Match mission script
    analyze_log(sys.argv[1])
